version: '3.4'


x-odoo:
  &default-odoo
  tty: true  # Do not avoid json logging
  build:
    image: "${IMAGE}:${ODOO_VERSION}-dev"
    context: "${FROMREPO}#master:images/dev"
    ports: ['80:8069', '8072:8072']
  volumes:
  # Named Data volumes
  - odoo-data:/var/lib/odoo-persist
  - odoo-backup:/var/lib/odoo-backup
  - odoo-testlogs:/var/lib/odoo-testlogs
  # Host paths (config)
  - .cfg-default.ini:/opt/odoo/.odoorc.d/01-default:ro
  - .cfg-custom.ini:/opt/odoo/.odoorc.d/02-custom:ro
  # Host paths (source)
  - ./src:/opt/odoo/addons/090
  - ./vendor/odoo/cc/odoo:/opt/odoo/odoo:ro
  - ./vendor/odoo/cc/addons:/opt/odoo/addons/000:ro
  - ./vendor/odoo/ee:/opt/odoo/addons/001:ro

secrets:
  adminpwd:
    file: .adminpwd

volumes:
  odoo-data: {driver: local}
  odoo-backup: {driver: local}
  odoo-testlogs: {driver: local}
  psql: {driver: local}

services:

# ========================

  wdb:
    image: xoes/wdb-server
    ports: ['1984:1984']

# ------------------------

  postgres:
    image: 'postgresql'
    volumes: ['psql:/var/lib/postgresql/data']
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    networks:
      default:
        aliases:
         - db

# ------------------------

  odoo:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    command: []
    build:
      args:
        FROM_IMAGE: "${FROM}:${ODOO_VERSION}"
      context: .
    depends_on: ['postgres', 'wdb']
    secrets:
      - source: adminpwd
        target: /run/secrets/adminpwd

# ========================

  scaffold:
    << : *default-odoo
    user: "${COMPOSE_IMPERSONATION}"
    entrypoint: ['/entrypoint.sh', 'scaffold']
    command: []

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--stop-after-init', '--logfile', '/testlogs/']
    command: []

# ------------------------

  shell:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh', 'shell']
    command: []

# ------------------------

  # migrate:
  #   << : *default-odoo
  #   depends_on: ['postgres', 'wdb']
  #   entrypoint: ['/entrypoint.sh', 'migrate']
  #   command: []

# ------------------------

  # initdb:
  #   << : *default-odoo
  #   depends_on: ['postgres', 'wdb']
  #   entrypoint: ['/entrypoint.sh', 'initdb']
  #   command: []

# ------------------------

  # load:
  #   << : *default-odoo
  #   depends_on: ['postgres', 'wdb']
  #   entrypoint: ['/entrypoint.sh', 'loader']
  #   command: []

# ------------------------

  # translate:
  #   << : *default-odoo
  #   depends_on: ['postgres', 'wdb']
  #   entrypoint: ['/entrypoint.sh', 'translate']
  #   command: []

# ------------------------
# TODO: move to Makefile

  view-patches:
    image: "${IMAGE}:${ODOO_VERSION}"
    entrypoint: []
    command: ['cat', '/patches']

# ------------------------

  patches:
    image: "${IMAGE}:${ODOO_VERSION}"
    user: "${COMPOSE_IMPERSONATION}"
    volumes:
      - ./vendor/odoo/cc:/mnt/cc-host-folder
    entrypoint: []
    command: ['/patches', '/mnt/cc-host-folder']